### ISSUE TITLE
sql query problem?

### ISSUE THREAD

**Issue by alleory** [rorystandley/MySQL-CRUD-PHP-OOP#17]
How can i use the query after your methoud??

My methoud of use
$sql = "SELECT * FROM news where id="$id" LIMIT 1";

how can i do it with this methoud???
<?php
include('class/mysql_crud.php');
$db = new Database();
$db->connect();
$db->select('CRUDClass','id,name','name="Name 1"','id DESC'); // Table name, Column Names, WHERE conditions, ORDER BY conditions
$res = $db->getResult();

i tried but i does not work, how you use the LIMIT????

<?php
include('class/mysql_crud.php');
$db = new Database();
$db->connect();
$db->select('news', LIMIT 1);
$res = $db->getResult();

**Comment by rorystandley** [comment]
Try this

$db->select('news', '*' ,'id='.$id, 1);

**Comment by alleory** [comment]
Thanks a lot :+1: now can i understand

**Comment by alleory** [comment]
it says 

Array ( [0] => You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'FROM crud_news LIMIT 1' at line 1 )????

**Comment by rorystandley** [comment]
You'd have to put he code you are using on here






On Tue, Aug 25, 2015 at 2:27 AM -0700, "alleory" <notifications@github.com> wrote:












it says 



Array ( [0] => You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'FROM crud_news LIMIT 1' at line 1 )????

**Comment by alleory** [comment]
$db->select('crud_news','','','','',1); 

Array ( [0] => You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'FROM crud_news LIMIT 1' at line 1 )

**Comment by rorystandley** [comment]
Have you written SQL before?
You will need to put he columns you require in your statement at least






On Tue, Aug 25, 2015 at 2:31 AM -0700, "alleory" <notifications@github.com> wrote:












$db->select('crud_news','','','','',1); 



Array ( [0] => You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'FROM crud_news LIMIT 1' at line 1 )

**Comment by alleory** [comment]
Tis is my whole code

<?php
include('class/crud.php');
$db = new Database();
$db->connect();
$db->select('crud_news','','','','',1); // Table name
$res = $db->getResult();
?>

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="">
        <meta name="author" content="">
        <link rel="icon" href="../../favicon.ico">

        <title>CRUD examples</title>
        <link href="css/bootstrap.css" rel="stylesheet" type="text/css"/>
        <link href="css/bootstrap-theme.css" rel="stylesheet" type="text/css"/>
        <link href="css/main.css" rel="stylesheet" type="text/css"/>
    </head> 

    <body>

        <div class="container">

            
            <nav class="navbar navbar-default">
                <div class="container-fluid">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <a class="navbar-brand" href="#">Project name</a>
                    </div>
                    <div id="navbar" class="navbar-collapse collapse">
                        <ul class="nav navbar-nav">
                            <li class="active"><a href="#">Home</a></li>
                            <li><a href="#">About</a></li>
                            <li><a href="#">Contact</a></li>
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
                                <ul class="dropdown-menu">
                                    <li><a href="#">Action</a></li>
                                    <li><a href="#">Another action</a></li>
                                    <li><a href="#">Something else here</a></li>
                                    <li role="separator" class="divider"></li>
                                    <li class="dropdown-header">Nav header</li>
                                    <li><a href="#">Separated link</a></li>
                                    <li><a href="#">One more separated link</a></li>
                                </ul>
                            </li>
                        </ul>
                        <ul class="nav navbar-nav navbar-right">
                            <li class="active"><a href="./">Default <span class="sr-only">(current)</span></a></li>
                            <li><a href="../navbar-static-top/">Static top</a></li>
                            <li><a href="../navbar-fixed-top/">Fixed top</a></li>
                        </ul>
                    </div>
                </div>
            </nav>

            <div class="jumbotron">
                <h1>Navbar example</h1>
                <p>This example is a quick exercise to illustrate how the default, static navbar and fixed to top navbar work. It includes the responsive CSS and HTML, so it also adapts to your viewport and device.</p>
                <p>
                    <a class="btn btn-lg btn-primary" href="../../components/#navbar" role="button">View navbar docs &raquo;</a>
                </p>
            </div>

            <div class="row">
                
                <?php
                
                foreach ($res as $row){
                    
                ?>
                
                <div class="col-xs-6 col-lg-4">
                    <p><img src="img/<?php echo $row['img']; ?>"></p>
                    <h2><?php echo $row['title']; ?></h2>
                    <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
                    <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
                </div>
                
                <?php
                
                }
                   
                ?>
               

            </div>
            <hr>

            <footer>
                <p>&copy; Company 2014</p>
            </footer>
        </div>


    </div> 

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script src="../../dist/js/bootstrap.min.js"></script>
    <script src="../../assets/js/ie10-viewport-bug-workaround.js"></script>
</body>
</html>

**Comment by rorystandley** [comment]
You still need to specify the column names you want in the query...

There are no issues with the class...

**Comment by alleory** [comment]
Yes i did it i said that i want to output all from crud_news table LIMIT 1

**Comment by rorystandley** [comment]
In the second argument you have an empty string. This should have column names or at least *






On Tue, Aug 25, 2015 at 2:37 AM -0700, "alleory" <notifications@github.com> wrote:












Yes i did it i said that i want to output all from crud_news table LIMIT 1

**Comment by alleory** [comment]
I did it like this $db->select('crud_news','*','','','',1); // Table name and it works, but how can i use ORDER BY ASC???

I tried like $db->select('crud_news','*','','','ASC',''); is it correct??
